[package]
name = "sigil-dioxus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sigil-core.workspace = true
dioxus.workspace = true
serde.workspace = true
serde_json.workspace = true
